app/models.py
from sqlalchemy.orm import declarative_base, Mapped, mapped_column, relationship
from sqlalchemy import String, DateTime, func, ForeignKey
from typing import List

Base = declarative_base()


class User(Base):
    __tablename__ = 'users'
    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(String(30), unique=True)
    password: Mapped[str] = mapped_column(String(256))
    basket: Mapped[List['Picture']] = relationship(cascade='all')
    pictures: Mapped[str] = mapped_column(ForeignKey('pictures.id'), nullable=True)


class Picture(Base):
    __tablename__ = 'pictures'
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(200))
    description: Mapped[str] = mapped_column(String(10000))
    uri: Mapped[str] = mapped_column(String(10000))
    price: Mapped[float]
    collection: Mapped[List['Collection']] = relationship(back_populates='pictures', cascade='all')
    collection_id: Mapped[str] = mapped_column(ForeignKey('collections.id'))
    created_at: Mapped[str] = mapped_column(DateTime(), server_default=func.now())


class Collection(Base):
    __tablename__ = 'collections'
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(200))
    description: Mapped[str] = mapped_column(String(10000))
    preview: Mapped[str] = mapped_column(String(1000))
    pictures: Mapped[List['Picture']] = relationship(back_populates='collection', cascade='all')

app/__init__.py
from flask import Flask, g
import os
from app.utils import get_user

app = Flask(__name__)
app.config['SECRET_KEY'] = '123'
app.config['UPLOAD_FOLDER'] = os.path.join(os.path.dirname(__file__), 'static/pictures')


@app.before_request
@get_user
def before_request(user):
    g.user = user


from app import main, auth, panel
app.register_blueprint(main.bp)
app.register_blueprint(auth.bp)
app.register_blueprint(panel.bp)


from app.commands import fill
app.cli.add_command(fill)

app/main/__init__.py
from flask import Blueprint
from .routes import index
from . import gallery

bp = Blueprint('main', __name__)

bp.add_url_rule('/', 'index', index, methods=['GET'])

bp.register_blueprint(gallery.bp)

app/main/gallery/__init__.py
from flask import Blueprint
from .routes import collections

bp = Blueprint('gallery', __name__, url_prefix='/gallery')

bp.add_url_rule('/', 'index', collections, methods=['GET'])

app/main/gallery/routes.py
def collections():
    return '1'


def pictures():
    return '1'


def picture():
    return '1'

app/main/routes.py
from flask import render_template
from app.models import Collection
from app.db import session


def index():
    collections = session.query(Collection).limit(5).all()
    return render_template('index.html', collections=collections)

app/panel/__init__.py
from flask import Blueprint
from .routes import index, create_picture, create_collection, update_picture, update_collection, delete_picture, \
    delete_collection

bp = Blueprint('panel', __name__, url_prefix='/panel', template_folder='panel')
bp.add_url_rule('/', 'index', index, methods=['GET'])
bp.add_url_rule('/picture/create', 'create_picture', create_picture, methods=['GET', 'POST'])
bp.add_url_rule('/collection/create', 'create_collection', create_collection, methods=['GET', 'POST'])
bp.add_url_rule('/picture/update', 'update_picture', update_picture, methods=['POST'])
bp.add_url_rule('/collection/update', 'update_collection', update_collection, methods=['POST'])
bp.add_url_rule('/picture/delete', 'delete_picture', delete_picture, methods=['POST'])
bp.add_url_rule('/collection/delete', 'delete_collection', delete_collection, methods=['POST'])

app/panel/routes.py
from flask import render_template, request, redirect, url_for, flash
from slugify import slugify
from app import app
import os
from app.models import Picture, Collection
from app.db import session
from app.utils import admin_required


@admin_required
def index():
    collections = session.query(Collection).all()
    return render_template('panel/index.html', collections=collections)


@admin_required
def create_picture():
    if request.method == 'GET':
        collections = session.query(Collection).all()
        return render_template('panel/picture.html', collections=collections)

    name = request.form.get('name')
    desc = request.form.get('description')
    price = request.form.get('price')
    collection_id = request.form.get('collection_id')

    file = request.files.get('picture')
    filetype = file.content_type.split('/')[1]
    name_ = slugify(request.form.get('name'), separator="_")
    filename = f"{name_}.{filetype}"
    file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
    if collection_id:
        picture = Picture(name=name, description=desc, uri=filename, price=price, collection_id=collection_id)
    else:
        picture = Picture(name=name, description=desc, uri=filename, price=price)
    session.add(picture)
    session.commit()

    flash('Picture uploaded at')
    return redirect(url_for('panel.index'))


@admin_required
def create_collection():
    if request.method == 'GET':
        return render_template('panel/collection.html')
    #  Creating new collection
    c_name = request.form.get('collection_name')
    c_desc = request.form.get('collection_description')

    preview = request.files.get('collection_preview')
    filetype = preview.content_type.split('/')[1]
    name_ = slugify(str(preview.filename), separator="_")
    filename = f"{name_}.{filetype}"
    preview.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

    collection = Collection(name=c_name, description=c_desc, preview=filename)
    session.add(collection)
    session.commit()
    #  Creating new pictures
    group_length = 3
    data = request.form

    for i in range(1, len(data) // group_length + 1):
        group_keys = [f'name_{i}', f'description_{i}', f'price_{i}']
        group_values = [data[key] for key in group_keys]

        file = request.files.get(f'picture_{i}')
        filetype = file.content_type.split('/')[1]
        fname_ = slugify(str(group_values[0]), separator="_")
        filename = f"{fname_}.{filetype}"
        file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

        new_picture = Picture(
            name=group_values[0],
            description=group_values[1],
            uri=filename,
            price=group_values[2],
            collection_id=collection.id
        )

        session.add(new_picture)
        session.commit()

    return redirect(url_for('panel.index'))


@admin_required
def update_picture():
    data = request.form.keys()
    return f'{data}'


@admin_required
def update_collection():
    return 'edit collection'


@admin_required
def delete_picture():
    return 'delete picture'


@admin_required
def delete_collection():
    return 'delete collection'

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% if title %}
    <title>{{ title }} - FilippArt</title>
    {% else %}
    <title>Welcome to FilippArt!</title>
    {% endif %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
{% block scripts %}
{% endblock %}
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
<div class="header">
    <div class="logo" id="logo">
        <img src="{{ url_for('static', filename='icons/logo.svg') }}" alt="brand">
    </div>
    <div class="dropdown">
        <button class="dropbtn">Gallery <i class="fa fa-caret-down"></i></button>
        <div class="dropdown-content">
            <a href="#">Collection 2024</a>
            <a href="#">Collection 2023</a>
            <a href="#">Collection 2022</a>
            <a href="#">Collection 2021</a>
            <a href="#">Collection 2020</a>
        </div>
    </div>
    <a href="#">About</a>
    <a href="#">Reviews</a>
    <a href="#">Contacts</a>
    <a href="#">FAQ</a>
    {% if g.user %}
        {% if g.user.username == 'admin' %}
            <a href="{{ url_for('panel.index') }}">{{ g.user.username }}</a>
        {% else %}
            <a href="#">{{ g.user.username }}</a>
        {% endif %}
    {% else %}
        <a href="{{ url_for('auth.login') }}">Login</a>
    {% endif %}

</div>
<div class="wrapper">

    <div class="container">
        <div class="product">
            <img src="{{ url_for('static', filename='pictures/image.png') }}" alt="Example">
            <div class="info">
                <h1>Collection name</h1>
                <div class="description">
                    consectetur adipisicing elit. Quia, iusto temporibus.
                    Fugit dolores architecto qui sit ea vitae, voluptate
                    omnis esse odit sapiente inventore, quaerat autem mollitia
                    velit beatae nam?
                </div>
                <div class="order">
                    <a href="#">Go to gallery</a>
                </div>
            </div>
        </div>
        <div class="product">
            <div class="info right">
                <h1>Your own idea</h1>
                <div class="description">
                    consectetur adipisicing elit. Quia, iusto temporibus.
                    Fugit dolores architecto qui sit ea vitae, voluptate
                    omnis esse odit sapiente inventore, quaerat autem mollitia
                    velit beatae nam?
                </div>
                <div class="order">
                    <a href="#">Go to gallery</a>
                </div>
            </div>
            <img src="{{ url_for('static', filename='pictures/image.png') }}" alt="Example">
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/onload.js') }}"></script>
{% endblock %}

app/templates/main/pictures.html
{% if pictures %}
{% for picture in pictures %}
<p>
    <img src="{{ url_for('static', filename='pictures/' + picture.uri) }}" alt="{{ picture.name }}" style="width: 200px;"><br>
    Name: <strong>{{ picture.name }}</strong><br>
    Description: <strong>{{ picture.description }}</strong>
</p>
<hr>
{% endfor %}
{% else %}
No pictures yet
{% endif %}

app/templates/panel/collection.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/panel/collection.css') }}">
<title>Create collection</title>
</head>
<body>
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            <div class="menu">
                <label for="collection_preview">
                    <img src="{{ url_for('static', filename='icons/picture.svg') }}" alt="Picture frame">
                </label>
                <input type="file" class="hidden" id="collection_preview" name="collection_preview" onchange="previewImage(this)">
                <input type="text" class="heavy" name="collection_name" placeholder="Collection name" required>
                <button class="info" id="addBtn" type="button"> + Add picture</button>
                <textarea id="collection_description" name="collection_description" placeholder="Collection description"></textarea>
                <button class="success" type="submit">✓ Create collection</button>
            </div>
            <div class="content" id="content">

<!--                  <div class="card">-->
<!--                      <div class="col-left">-->
<!--                          <label for="picture_preview">-->
<!--                              <img src="{{ url_for('static', filename='icons/picture.svg') }}" alt="Picture frame">-->
<!--                          </label>-->
<!--                          <input type="file" class="hidden" id="picture_preview">-->
<!--                          <input type="text" class="heavy" placeholder="Picture name">-->
<!--                          <input type="number" placeholder="Price">-->
<!--                          <button class="warning" type="button">✖ Delete picture</button>-->
<!--                      </div>-->
<!--                      <div class="col-right">-->
<!--                          <textarea placeholder="Picture description"></textarea>-->
<!--                      </div>-->
<!--                  </div>-->

              </div>
        </form>
    </div>

          <!--<form id="uploadForm" method="post" enctype="multipart/form-data">-->
<!--  <div class="header">-->
<!--    <input type="file" name="collection_preview">-->
<!--    <input type="text" name="collection_name" placeholder="Collection name" required>-->
<!--    <input type="text" name="collection_description" placeholder="Collection description" required>-->
<!--    <button type="button" onclick="addInput()">+ Add picture</button>-->
<!--    <button>✓ Create collection</button>-->
<!--  </div>-->
<!--</form>-->
<script src="{{ url_for('static', filename='js/panel/collection.js') }}"></script>
</body>
</html>

app/templates/panel/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/panel.css') }}">
    <title>JOPA</title>
</head>
<body>
    <div class="container">
        <div class="header">
            <a href="{{ url_for('panel.create_collection') }}">Create collection</a>
            <a href="{{ url_for('panel.create_picture') }}">Create picture</a>
            <a href="{{ url_for('auth.logout') }}" style="color: red;">Logout</a>
        </div>
        {% if collections %}
            {% for collection in collections %}
                <div class="card">
                    <div class="collection">
                        <img src="{{ url_for('static', filename='pictures/' + collection.preview) }}" alt="Image">
                        <div class="info">
                            <span>
                                <h1 onclick="toggleDescription(this)">Name: {{ collection.name }}</h1>
                                <p>Description: {{ collection.description }}</p>
                            </span>
                            <form method="post">
                                <input type="text" placeholder="Name">
                                <textarea placeholder="Description"></textarea>
                                <button>Update</button>
                            </form>
                            <form>
                                <button style="color: red; padding: 5px 30px 5px 30px">Delete</button>
                            </form>
                        </div>
                    </div>
                    {% for picture in collection.pictures %}
                    <div class="pictures">
                        <div class="small-card">
                            <img src="{{ url_for('static', filename='pictures/' + picture.uri) }}" alt="Image">
                            <div class="info">
                                <span>
                                    <h1>Name: {{ picture.name }}</h1>
                                    <p>Description: {{ picture.description }}</p>
                                    <p>Price: ${{ picture.price }}</p>
                                </span>
                                <form onsubmit="return false;" id="pic_{{ picture.id }}">
                                    <input type="text" id="pic_name_{{ picture.id }}" placeholder="Name">
                                    <input type="text" id="pic_desc_{{ picture.id }}" placeholder="Description">
                                    <input type="number" id="pic_price_{{ picture.id }}" placeholder="Price">
                                    <button onclick="updatePicture({{ picture.id }}); return false;">Update</button>
                                </form>
                                <form method="post">
                                    <button style="color: red; padding: 5px 30px 5px 30px">Delete</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% endfor %}
        {% else %}
        Collections is not even uploaded.
        {% endif %}
    </div>
</body>
<script>
    function toggleDescription(card) {
        card.parentNode.parentNode.parentNode.parentNode.classList.toggle('active');
    }

    async function updatePicture (id) {
        const name = document.getElementById(`pic_name_${id}`).value
        const desc = document.getElementById(`pic_desc_{id}`).value
        const price = document.getElementById(`pic_price_${id}`).value

    }
</script>
</html>

app/templates/panel/picture.html
<form method="post" enctype="multipart/form-data">
    <input type="file" accept="image/*" name="picture" id="imgInp" required />
    <input type="text" name="name" placeholder="Name" required>
    <input type="text" name="description" placeholder="Description" required>
    <input type="number" name="price" placeholder="Price" required>
    {% if collections %}
    <select name="collection_id">
        <option value="0" selected>Without collection</option>
        {% for collection in collections %}
        <option value="{{ collection.id }}">{{ collection.name }}</option>
        {% endfor %}
    </select>
    {% endif %}
    <button>Upload picture</button>
</form>
<img id="blah" src="#" alt="your image" style="max-width: 600px; display: none"/>
<script>
    imgInp.onchange = evt => {
        const [file] = imgInp.files
        if (file) {
            blah.src = URL.createObjectURL(file)
            blah.style.display = 'block'
        }
    }
</script>